# Netlify build configuration for your Next.js project

[build]
  # Command to build your Next.js project.
  # This should match the "build" script in your package.json.
  command = "npm run build"
  
  # The directory that Netlify will publish.
  # For Next.js projects using the Netlify plugin, this is typically ".next".
  # The plugin often handles this automatically.
  publish = ".next"

# Configuration for the Netlify Next.js plugin.
# This plugin is essential for deploying Next.js sites with features like
# server-side rendering, ISR, API routes, and image optimization on Netlify.
# It will be installed automatically during the build if not in your package.json.
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Optional: Specify the Node.js version for the build environment.
# Your package.json specifies "node": ">=16.x".
# You can set a specific LTS version supported by Netlify.
[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_TRACKING_ID = "G-XXXXXXXXXX"  # Replace with your actual GA4 ID

  # Environment variables:
  # You can set your NEXT_PUBLIC_ environment variables here if they are not sensitive,
  # or preferably manage all environment variables (especially secrets) 
  # through the Netlify UI under Site settings > Build & deploy > Environment.
  #
  # Example structure (replace with your actual values if you choose this method):
  # NEXT_PUBLIC_TRACKING_ID = "G-XXXXXXXXXX"
  # NEXT_PUBLIC_GEMINI_API_KEY = "AIzaSyBqrJpN-6p32FZ-O--w7LA5cFjA9YJmK90"
  # NEXT_PUBLIC_SERVICE_ID = "your_service_id"
  # NEXT_PUBLIC_TEMPLATE_ID = "your_template_id"
  # NEXT_PUBLIC_USER_ID = "your_user_id"

# Optional: Redirects and rewrites
# For more information, see https://docs.netlify.com/routing/redirects/
# [[redirects]]
#   from = "/old-page"
#   to = "/new-page"
#   status = 301

# Optional: Custom headers
# For more information, see https://docs.netlify.com/routing/headers/
# [[headers]]
#   for = "/*"
#   [headers.values]
#     X-Content-Type-Options = "nosniff"